# Generated by Django 4.0.4 on 2022-05-20 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('primary_lightning_address', models.CharField(max_length=500)),
                ('payment_split_lightning_addresses', models.JSONField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_splitting.status')),
            ],
        ),
    ]
